### PR TITLE
Add support for dynamic metadata

### PR DESCRIPTION
**Pull request by lolwatks**

### CODE REVIEW

**Comment by lolwatks** [comment]
I accept the CLA

**Comment by lolwatks** [comment]
I accept the cla

**Comment by Cephalopterus** [comment]
@cla-bot check now

**Comment by lolwatks** [comment]
@cla-bot check now

**Comment by lolwatks** [comment]
I accept the CLA

**Comment by takeda-discord** [comment]
@cla-bot check now

**Pull request merged**
